customer_id: bbi
display_name: BBI
sso_session: sadewa-sso

slack:
  webhook_url: ""
  channel: ""
  enabled: false

checks:
  - health
  - cost
  - guardduty
  - cloudwatch

accounts:
  - profile: bbi
    account_id: "940404076348"
    display_name: "BBI"
    region: ap-southeast-1
