customer_id: edot
display_name: Edot
sso_session: sadewa-sso

slack:
  webhook_url: ""
  channel: ""
  enabled: false

checks:
  - health
  - cost
  - guardduty
  - cloudwatch

accounts:
  - profile: edot
    account_id: "261622543538"
    display_name: "Edot"
    region: ap-southeast-1
