customer_id: rumahmedia
display_name: RumahMedia
sso_session: null

slack:
  webhook_url: ""
  channel: ""
  enabled: false

checks:
  - health
  - cost
  - guardduty
  - cloudwatch

accounts:
  - profile: rumahmedia
    account_id: ""
    display_name: "RumahMedia"
    region: ap-southeast-2
