type: object
required:
  - customer_id
  - accounts
properties:
  customer_id:
    type: string
  display_name:
    type: string
  accounts:
    type: array
    minItems: 1
    items:
      type: object
      required:
        - account_id
      properties:
        profile:
          type: string
        account_id:
          type: string
        display_name:
          type: string
        daily_arbel:
          type: object
          properties:
            cluster_id:
              type: [string, "null"]
            instances:
              type: object
            metrics:
              type: array
              items:
                type: string
            thresholds:
              type: object
