customer_id: aryanoble
display_name: Aryanoble

accounts:
  - profile: connect-prod
    account_id: "620463044477"
    display_name: "CONNECT Prod (Non CIS)"
    daily_arbel:
      cluster_id: noncis-prod-rds
      instances:
        writer: null
      metrics:
        - ACUUtilization
        - CPUUtilization
        - FreeableMemory
        - DatabaseConnections
      thresholds:
        FreeableMemory: 10737418240
        ACUUtilization: 75
        CPUUtilization: 75
        DatabaseConnections: 1500

  - profile: cis-erha
    account_id: "451916275465"
    display_name: "CIS ERHA"
    daily_arbel:
      cluster_id: cis-prod-rds
      instances:
        writer: cis-prod-rds-instance
        reader: cis-prod-rds-instance-reader
      metrics:
        - ACUUtilization
        - CPUUtilization
        - FreeableMemory
        - DatabaseConnections
      thresholds:
        FreeableMemory: 21474836480
        ACUUtilization: 75
        CPUUtilization: 75
        DatabaseConnections: 3000

  - profile: dermies-max
    account_id: "637423567244"
    display_name: "DERMIES MAX"
    daily_arbel:
      cluster_id: dermies-prod-rds
      instances:
        writer: dermies-prod-rds
        reader: dermies-prod-rds-reader
      metrics:
        - ACUUtilization
        - CPUUtilization
        - FreeableMemory
        - DatabaseConnections
      thresholds:
        FreeableMemory: 10737418240
        ACUUtilization: 75
        CPUUtilization: 75
        DatabaseConnections: 1500

  - profile: erha-buddy
    account_id: "486250145105"
    display_name: "ERHA BUDDY"
    daily_arbel:
      instances:
        prod: erhabuddy-prod-mysql-db
      metrics:
        - CPUUtilization
        - FreeableMemory
        - DatabaseConnections
        - FreeStorageSpace
      thresholds:
        FreeableMemory: 838860800
        CPUUtilization: 75
        DatabaseConnections: 500
        FreeStorageSpace: 10737418240

  - profile: public-web
    account_id: "211125667194"
    display_name: "PUBLIC WEB"
    daily_arbel:
      instances:
        mysql-prod: mysql-prod-instance
        postgre-prod: postgre-prod-instance
      metrics:
        - CPUUtilization
        - FreeableMemory
        - DatabaseConnections
        - FreeStorageSpace
      thresholds:
        FreeableMemory: 209715200
        CPUUtilization: 75
        DatabaseConnections: 500
        FreeStorageSpace: 5368709120

  - profile: dwh
    account_id: "084056488725"
    display_name: "DWH"

  - profile: genero-empower
    account_id: "941377160792"
    display_name: "GENERO EMPOWER"
